name: My panda ci
on: 
  push:
    branches: [main] # This will run everytime you push to the 'main' branch

jobs:
  builds:
      runs-on: ubuntu-latest
      name: my build
      steps:
        - name: Check out code
          uses: actions/checkout@v2 # This is actually a repo
        - name: Set up go
          uses: actions/setup-go@v5.2.0 # This is also a repo
          with: 
            go-version: 1.17.0
            check-latest: true # Always check for the latest available version
        - name: what is go version
          run: |
            go version
            ls
            go test -cover
